window.RYOTA_PROJECTS = [
  {
    id: "ehime-evacuation-risk-map",
    title: "南海トラフ・本当に逃げられるかマップ",
    description: "津波浸水想定と徒歩避難ネットワークから「本当に逃げられるか」を可視化。",
    categories: ["行政・防災", "GIS"],
    status: "live",
    host: "GitHub Pages",
    featured: 1,
    visual: "map",
    image: "assets/projects/ehime-evacuation-risk-map.webp",
    imagePosition: "50% 32%",
    imageAttribution: "© OpenStreetMap contributors",
    appUrl: "https://ryotamatsuki.github.io/ehime-evacuation-risk-map/",
    repoUrl: "https://github.com/ryotamatsuki/ehime-evacuation-risk-map"
  },
  {
    id: "ehime-mobility-resilience-lab",
    title: "Ehime Mobility Resilience Lab",
    description: "公共交通・道路・物流のネットワークを平時にストレステストするWebGIS。",
    categories: ["交通", "行政・防災", "GIS"],
    status: "live",
    host: "GitHub Pages",
    featured: 2,
    visual: "transit",
    image: "assets/projects/ehime-mobility-resilience-lab.webp",
    imagePosition: "50% 34%",
    imageAttribution: "© OpenStreetMap contributors",
    appUrl: "https://ryotamatsuki.github.io/ehime-mobility-resilience-lab/",
    repoUrl: "https://github.com/ryotamatsuki/ehime-mobility-resilience-lab"
  },
  {
    id: "ehime-kokubunsai-ai-poc",
    title: "愛顔えひめの文化祭 AI案内",
    description: "自然言語でイベントを探し、条件に合う文化体験を提案するAI案内PoC。",
    categories: ["AI", "行政・防災"],
    status: "poc",
    host: "Streamlit",
    featured: false,
    visual: "chat",
    appUrl: "https://ehime-kokubunsai-ai-poc-9uqr82g7mpllijkeewhky8.streamlit.app/",
    repoUrl: "https://github.com/ryotamatsuki/ehime-kokubunsai-ai-poc"
  },
  {
    id: "ehime-aed-rescue-map",
    title: "AED Rescue Map",
    description: "AED到達圏と次の1台の配置候補を、人口カバレッジから分析。",
    categories: ["行政・防災", "GIS"],
    status: "live",
    host: "GitHub Pages",
    featured: false,
    visual: "aed",
    image: "assets/projects/ehime-aed-rescue-map.webp",
    imagePosition: "50% 40%",
    imageAttribution: "© OpenStreetMap contributors",
    appUrl: "https://ryotamatsuki.github.io/ehime-aed-rescue-map/",
    repoUrl: "https://github.com/ryotamatsuki/ehime-aed-rescue-map"
  },
  {
    id: "yokaizukan",
    title: "妖怪図鑑",
    description: "日本の妖怪を、地域差・原典・物語性まで楽しめるインタラクティブ図鑑。",
    categories: ["教育", "ゲーム"],
    status: "live",
    host: "Web App",
    featured: false,
    visual: "yokai",
    image: "assets/projects/yokaizukan.webp",
    imagePosition: "66% 34%",
    appUrl: "https://ryotamatsuki.github.io/yokaizukan/",
    repoUrl: "https://github.com/ryotamatsuki/yokaizukan"
  },
  {
    id: "ehime-quiz",
    title: "Ehime Quiz",
    description: "愛媛に関するクイズで、地域の魅力を遊びながら再発見。",
    categories: ["ゲーム", "教育"],
    status: "live",
    host: "Web Game",
    featured: false,
    visual: "quiz",
    appUrl: "https://ryotamatsuki.github.io/ehime_quiz/",
    repoUrl: "https://github.com/ryotamatsuki/ehime_quiz"
  },
  {
    id: "furusatonozei",
    title: "ふるさと納税ダッシュボード",
    description: "自治体別の寄付受入・税控除・財政影響を比較できる可視化ダッシュボード。",
    categories: ["行政・防災", "GIS"],
    status: "live",
    host: "Web App",
    featured: 3,
    visual: "chart",
    image: "assets/projects/furusatonozei.webp",
    imagePosition: "56% 48%",
    appUrl: "https://ryotamatsuki.github.io/furusatonozei/",
    repoUrl: "https://github.com/ryotamatsuki/furusatonozei"
  },
  {
    id: "kumamotoshienmap",
    title: "熊本支援マップ",
    description: "災害時の支援ニーズと支援スポットをつなぐ情報マップ。",
    categories: ["行政・防災", "GIS"],
    status: "live",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    image: "assets/projects/kumamotoshienmap.webp",
    imagePosition: "50% 34%",
    appUrl: "https://ryotamatsuki.github.io/kumamotoshienmap/ehime_kumamoto_support_geocoded_shelters_20260802.html",
    repoUrl: "https://github.com/ryotamatsuki/kumamotoshienmap"
  },
  {
    id: "hime-star-journey",
    title: "Hime Star Journey",
    description: "ブラウザで遊べる、宇宙をテーマにした小さなアクションゲーム。",
    categories: ["ゲーム"],
    status: "live",
    host: "Web Game",
    featured: false,
    visual: "space",
    image: "assets/projects/hime-star-journey.webp",
    imagePosition: "50% 42%",
    appUrl: "https://ryotamatsuki.github.io/hime-star-journey/",
    repoUrl: "https://github.com/ryotamatsuki/hime-star-journey"
  },
  {
    id: "ehime-tour-planner",
    title: "Ehime Tour Planner",
    description: "愛媛観光の条件を対話で整理し、旅程候補を組み立てるAI観光アプリ。",
    categories: ["AI", "交通"],
    status: "live",
    host: "Streamlit",
    featured: false,
    visual: "chat",
    image: "assets/projects/ehime-tour-planner.webp",
    imagePosition: "55% 30%",
    appUrl: "https://ehime-tour-planner-iicqpkkbfs9zrcjba6a9at.streamlit.app/",
    repoUrl: "https://github.com/ryotamatsuki/ehime-tour-planner"
  },
  {
    id: "360panorama",
    title: "道後公園 時空360",
    description: "戦国期の湯築城を24地点の360度ウォークスルーで巡る歴史体験。",
    categories: ["教育", "GIS"],
    status: "live",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/360panorama/",
    repoUrl: "https://github.com/ryotamatsuki/360panorama"
  },
  {
    id: "star-wing",
    title: "STAR WING",
    description: "フルスクリーンで遊べるブラウザ向けシューティングゲーム。",
    categories: ["ゲーム"],
    status: "live",
    host: "Web Game",
    featured: false,
    visual: "space",
    appUrl: "https://ryotamatsuki.github.io/star-wing/",
    repoUrl: "https://github.com/ryotamatsuki/star-wing"
  },
  {
    id: "localgovernant",
    title: "LOCAL GOVERNMENT INC.",
    description: "架空自治体「青波市」を10年間経営する月次ターン制の自治体経営シミュレーション。",
    categories: ["ゲーム", "行政・防災"],
    status: "poc",
    host: "GitHub",
    featured: false,
    visual: "game",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/localgovernant"
  },
  {
    id: "ehime-tcg",
    title: "愛媛TCG Web MVP",
    description: "愛媛の地域モチーフを使った164種カード・4スターターのローカルCPU対戦型Webカードゲーム。",
    categories: ["ゲーム", "教育"],
    status: "poc",
    host: "GitHub",
    featured: false,
    visual: "game",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/ehime-tcg"
  },
  {
    id: "sarashina-chat",
    title: "Sarashina Chat",
    description: "Sarashina2.2-3B-InstructをStreamlitフロントエンドとModal GPUバックエンドで動かす実験。",
    categories: ["AI"],
    status: "poc",
    host: "GitHub",
    featured: false,
    visual: "chat",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/sarashina-chat"
  },
  {
    id: "bus-timelapse",
    title: "Bus Timelapse",
    description: "GTFSからバスの動きを時間軸で可視化する交通データ実験。",
    categories: ["交通", "GIS"],
    status: "poc",
    host: "GitHub",
    featured: false,
    visual: "bus",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/bus-timelapse"
  },
  {
    id: "kids-typing",
    title: "Kids Typing",
    description: "子ども向けに遊びながらキー入力を練習できるブラウザゲーム。",
    categories: ["ゲーム", "教育"],
    status: "live",
    host: "Web Game",
    featured: false,
    visual: "game",
    appUrl: "https://ryotamatsuki.github.io/kids_typing/",
    repoUrl: "https://github.com/ryotamatsuki/kids_typing"
  },
  {
    id: "retro-sky-raid",
    title: "Retro Sky Raid",
    description: "レトロな空戦表現を試したブラウザゲームプロトタイプ。",
    categories: ["ゲーム"],
    status: "archive",
    host: "Web Game",
    featured: false,
    visual: "space",
    image: "assets/projects/retro-sky-raid.webp",
    imagePosition: "50% 48%",
    appUrl: "https://ryotamatsuki.github.io/retro-sky-raid/",
    repoUrl: "https://github.com/ryotamatsuki/retro-sky-raid"
  },
  {
    id: "solar-system",
    title: "Solar System",
    description: "太陽系を題材にした3D・可視化表現の実験。",
    categories: ["教育", "ゲーム"],
    status: "archive",
    host: "Web App",
    featured: false,
    visual: "space",
    appUrl: "https://ryotamatsuki.github.io/solar_system/",
    repoUrl: "https://github.com/ryotamatsuki/solar_system"
  },
  {
    id: "aidai",
    title: "食事データダッシュボード",
    description: "食事・栄養データをStreamlitで集計し、カロリーや食行動を複数ビューで可視化する実験。",
    categories: ["AI", "教育"],
    status: "archive",
    host: "GitHub",
    featured: false,
    visual: "chart",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/aidai"
  },
  {
    id: "city-annalist",
    title: "みんなのまちAI風 MVP",
    description: "公開データによる都市分析・シナリオ比較・EBPM予算案作成を統合したStreamlit + FastAPI MVP。",
    categories: ["AI", "行政・防災", "GIS"],
    status: "archive",
    host: "GitHub",
    featured: false,
    visual: "chart",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/city_annalist"
  },
  {
    id: "minnnanomachiai",
    title: "みんなのまちAI風",
    description: "人口・産業・交通・防災の可視化、介入シミュレーション、根拠付き予算案を扱う公開データ実験。",
    categories: ["AI", "行政・防災", "GIS"],
    status: "archive",
    host: "GitHub",
    featured: false,
    visual: "map",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/minnnanomachiai"
  },
  {
    id: "3d-tsunami",
    title: "津波浸水想定区域 3D",
    description: "QGIS2threejsで津波浸水想定区域を3D表示するWebGISプロトタイプ。",
    categories: ["行政・防災", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/3d_tsunami/",
    repoUrl: "https://github.com/ryotamatsuki/3d_tsunami"
  },
  {
    id: "airportgolf",
    title: "松山空港・ゴルフ場 到達圏マップ",
    description: "松山空港を起点に移動時間等時線と愛媛のゴルフ場・観光地を重ねるMapbox実験。",
    categories: ["交通", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/airportgolf/",
    repoUrl: "https://github.com/ryotamatsuki/airportgolf"
  },
  {
    id: "cancertest",
    title: "がん検診対応医療機関マップ",
    description: "愛媛県内の医療機関と胃がん・大腸がん等の検診対応をLeaflet上に表示する地図。",
    categories: ["行政・防災", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/cancertest/",
    repoUrl: "https://github.com/ryotamatsuki/cancertest"
  },
  {
    id: "childcarematsuyama",
    title: "松山 子育て施設 到達圏マップ",
    description: "子育て支援施設と徒歩・自転車・車の到達圏を重ねるMapboxプロトタイプ。",
    categories: ["行政・防災", "交通", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/childcarematsuyama/",
    repoUrl: "https://github.com/ryotamatsuki/childcarematsuyama"
  },
  {
    id: "codextest-a",
    title: "愛媛県公式YouTube 分析ダッシュボード",
    description: "YouTube Data APIから動画を取得し、再生状況や公開時期、配信戦略の示唆を可視化する試作。",
    categories: ["行政・防災"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "chart",
    appUrl: "https://ryotamatsuki.github.io/codextest_a/",
    repoUrl: "https://github.com/ryotamatsuki/codextest_a"
  },
  {
    id: "imabarityme",
    title: "今治 観光到達圏マップ",
    description: "今治を起点に徒歩・自転車・車の移動時間等時線と観光地を重ねるMapbox実験。",
    categories: ["交通", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/imabarityme/",
    repoUrl: "https://github.com/ryotamatsuki/imabarityme"
  },
  {
    id: "kamijimatest",
    title: "上島町 観光PR Prototype",
    description: "上島町の観光スポット、名物料理、体験・アクティビティを紹介する観光サイト試作。",
    categories: ["教育"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/kamijimatest/",
    repoUrl: "https://github.com/ryotamatsuki/kamijimatest"
  },
  {
    id: "kamijimatoshi-v2",
    title: "上島町 投資誘致サイト Prototype",
    description: "企業版ふるさと納税、サテライトオフィス、官民連携などを題材にした投資誘致サイト試作。",
    categories: ["行政・防災"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "chart",
    appUrl: "https://ryotamatsuki.github.io/kamijimatoshi_v2/",
    repoUrl: "https://github.com/ryotamatsuki/kamijimatoshi_v2"
  },
  {
    id: "lpsample",
    title: "愛媛かんきつ LP Prototype A",
    description: "愛媛の柑橘を題材に、品種・農園ストーリー・ギフト導線を構成したランディングページ試作。",
    categories: ["教育"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "chart",
    appUrl: "https://ryotamatsuki.github.io/lpsample/",
    repoUrl: "https://github.com/ryotamatsuki/lpsample"
  },
  {
    id: "map-of-salesman-in-matsuyama-and-toon",
    title: "松山・東温 巡回ルートマップ",
    description: "松山市・東温市周辺の移動ルートをOpenStreetMap上に可視化したFolium地図。",
    categories: ["交通", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/map-of-salesman-in-matsuyama-and-toon/",
    repoUrl: "https://github.com/ryotamatsuki/map-of-salesman-in-matsuyama-and-toon"
  },
  {
    id: "matsuyamastationaroundmap",
    title: "JR松山駅周辺 整備マップ",
    description: "JR松山駅周辺の整備内容、主体、完成時期、整備ステップを切り替えて確認できるWebGIS。",
    categories: ["交通", "行政・防災", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/matsuyamastationaroundmap/",
    repoUrl: "https://github.com/ryotamatsuki/matsuyamastationaroundmap"
  },
  {
    id: "openstreet",
    title: "OpenStreet × おでかけウォッチャー Map",
    description: "おでかけウォッチャースポットとOpenStreetステーションを重ねたインタラクティブ地図。",
    categories: ["交通", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/openstreet/",
    repoUrl: "https://github.com/ryotamatsuki/openstreet"
  },
  {
    id: "orange",
    title: "愛媛柑橘 LP Prototype B",
    description: "愛媛柑橘の品種紹介や購入導線を題材にした別デザインのランディングページ試作。",
    categories: ["教育"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "chart",
    appUrl: "https://ryotamatsuki.github.io/orange/",
    repoUrl: "https://github.com/ryotamatsuki/orange"
  },
  {
    id: "qgisgaikokujin",
    title: "外国人関連データ WebGIS v1",
    description: "行政施設等の地理データを含む外国人関連分析用レイヤをQGIS2Webで公開したWebGIS初期版。",
    categories: ["行政・防災", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/qgisgaikokujin/",
    repoUrl: "https://github.com/ryotamatsuki/qgisgaikokujin"
  },
  {
    id: "qgisgaikokujin2",
    title: "外国人関連データ WebGIS v2",
    description: "QGIS2WebとLeafletで構成した外国人関連分析用WebGISの改良版。",
    categories: ["行政・防災", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/qgisgaikokujin2/",
    repoUrl: "https://github.com/ryotamatsuki/qgisgaikokujin2"
  },
  {
    id: "ryota-openstreet",
    title: "OpenStreet Map Variant",
    description: "OpenStreetステーション等の地点データをFoliumで表示した別リポジトリ版。",
    categories: ["交通", "GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/ryota.openstreet/",
    repoUrl: "https://github.com/ryotamatsuki/ryota.openstreet"
  },
  {
    id: "sample-antigrabity",
    title: "Super Pixel Adventure",
    description: "Canvasで動くレトロ調2D横スクロール・プラットフォーマーのゲーム試作。",
    categories: ["ゲーム"],
    status: "archive",
    host: "GitHub",
    featured: false,
    visual: "game",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/sample_antigrabity"
  },
  {
    id: "webgis",
    title: "GIS Visualization Tool",
    description: "GeoJSONやShapefileを読み込み、レイヤ管理とスタイル設定をブラウザで試せるGISツール。",
    categories: ["GIS"],
    status: "archive",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/webgis/",
    repoUrl: "https://github.com/ryotamatsuki/webgis"
  },
  {
    id: "writepaper-public-co-creation-hubs",
    title: "Public Co-creation Hubs Research",
    description: "地域の共創拠点を扱う研究論文・解説資料・投稿用ソースを公開した研究リポジトリ。",
    categories: ["Research"],
    status: "archive",
    host: "GitHub",
    featured: false,
    visual: "chart",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/writepaper_public_co-creation_hubs"
  }
];
