window.RYOTA_PROJECTS = [
  {
    id: "ehime-evacuation-risk-map",
    title: "南海トラフ・本当に逃げられるかマップ",
    description: "津波浸水想定と徒歩避難ネットワークから「本当に逃げられるか」を可視化。",
    categories: ["行政・防災", "GIS"],
    status: "live",
    host: "GitHub Pages",
    featured: 1,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/ehime-evacuation-risk-map/",
    repoUrl: "https://github.com/ryotamatsuki/ehime-evacuation-risk-map"
  },
  {
    id: "ehime-mobility-resilience-lab",
    title: "Ehime Mobility Resilience Lab",
    description: "公共交通・道路・物流のネットワークを平時にストレステストするWebGIS。",
    categories: ["交通", "行政・防災", "GIS"],
    status: "live",
    host: "GitHub Pages",
    featured: 2,
    visual: "transit",
    appUrl: "https://ryotamatsuki.github.io/ehime-mobility-resilience-lab/",
    repoUrl: "https://github.com/ryotamatsuki/ehime-mobility-resilience-lab"
  },
  {
    id: "ehime-kokubunsai-ai-poc",
    title: "愛顔えひめの文化祭 AI案内",
    description: "自然言語でイベントを探し、条件に合う文化体験を提案するAI案内PoC。",
    categories: ["AI", "行政・防災"],
    status: "poc",
    host: "Streamlit",
    featured: 3,
    visual: "chat",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/ehime-kokubunsai-ai-poc"
  },
  {
    id: "ehime-aed-rescue-map",
    title: "AED Rescue Map",
    description: "AED到達圏と次の1台の配置候補を、人口カバレッジから分析。",
    categories: ["行政・防災", "GIS"],
    status: "live",
    host: "GitHub Pages",
    featured: false,
    visual: "aed",
    appUrl: "https://ryotamatsuki.github.io/ehime-aed-rescue-map/",
    repoUrl: "https://github.com/ryotamatsuki/ehime-aed-rescue-map"
  },
  {
    id: "yokaizukan",
    title: "妖怪図鑑",
    description: "日本の妖怪を、地域差・原典・物語性まで楽しめるインタラクティブ図鑑。",
    categories: ["教育", "ゲーム"],
    status: "live",
    host: "Web App",
    featured: false,
    visual: "yokai",
    appUrl: "https://ryotamatsuki.github.io/yokaizukan/",
    repoUrl: "https://github.com/ryotamatsuki/yokaizukan"
  },
  {
    id: "ehime-quiz",
    title: "Ehime Quiz",
    description: "愛媛に関するクイズで、地域の魅力を遊びながら再発見。",
    categories: ["ゲーム", "教育"],
    status: "live",
    host: "Web Game",
    featured: false,
    visual: "quiz",
    appUrl: "https://ryotamatsuki.github.io/ehime_quiz/",
    repoUrl: "https://github.com/ryotamatsuki/ehime_quiz"
  },
  {
    id: "furusatonozei",
    title: "ふるさと納税ダッシュボード",
    description: "自治体別の寄付受入・税控除・財政影響を比較できる可視化ダッシュボード。",
    categories: ["行政・防災", "GIS"],
    status: "live",
    host: "Web App",
    featured: false,
    visual: "chart",
    appUrl: "https://ryotamatsuki.github.io/furusatonozei/",
    repoUrl: "https://github.com/ryotamatsuki/furusatonozei"
  },
  {
    id: "kumamotoshienmap",
    title: "熊本支援マップ",
    description: "災害時の支援ニーズと支援スポットをつなぐ情報マップ。",
    categories: ["行政・防災", "GIS"],
    status: "live",
    host: "GitHub Pages",
    featured: false,
    visual: "map",
    appUrl: "https://ryotamatsuki.github.io/kumamotoshienmap/",
    repoUrl: "https://github.com/ryotamatsuki/kumamotoshienmap"
  },
  {
    id: "hime-star-journey",
    title: "Hime Star Journey",
    description: "ブラウザで遊べる、宇宙をテーマにした小さなアクションゲーム。",
    categories: ["ゲーム"],
    status: "live",
    host: "Web Game",
    featured: false,
    visual: "space",
    appUrl: "https://ryotamatsuki.github.io/hime-star-journey/",
    repoUrl: "https://github.com/ryotamatsuki/hime-star-journey"
  },
  {
    id: "ehime-tour-planner",
    title: "Ehime Tour Planner",
    description: "愛媛観光の条件を対話で整理し、旅程候補を組み立てるAI観光アプリ。",
    categories: ["AI", "交通"],
    status: "live",
    host: "Streamlit",
    featured: false,
    visual: "chat",
    appUrl: "https://ehime-tour-planner-iicqpkkbfs9zrcjba6a9at.streamlit.app/",
    repoUrl: "https://github.com/ryotamatsuki/ehime-tour-planner"
  },
  {
    id: "bus-timelapse",
    title: "Bus Timelapse",
    description: "GTFSからバスの動きを時間軸で可視化する交通データ実験。",
    categories: ["交通", "GIS"],
    status: "poc",
    host: "GitHub",
    featured: false,
    visual: "bus",
    appUrl: null,
    repoUrl: "https://github.com/ryotamatsuki/bus-timelapse"
  },
  {
    id: "kids-typing",
    title: "Kids Typing",
    description: "子ども向けに遊びながらキー入力を練習できるブラウザゲーム。",
    categories: ["ゲーム", "教育"],
    status: "live",
    host: "Web Game",
    featured: false,
    visual: "game",
    appUrl: "https://ryotamatsuki.github.io/kids_typing/",
    repoUrl: "https://github.com/ryotamatsuki/kids_typing"
  },
  {
    id: "retro-sky-raid",
    title: "Retro Sky Raid",
    description: "レトロな空戦表現を試したブラウザゲームプロトタイプ。",
    categories: ["ゲーム"],
    status: "archive",
    host: "Web Game",
    featured: false,
    visual: "space",
    appUrl: "https://ryotamatsuki.github.io/retro-sky-raid/",
    repoUrl: "https://github.com/ryotamatsuki/retro-sky-raid"
  },
  {
    id: "solar-system",
    title: "Solar System",
    description: "太陽系を題材にした3D・可視化表現の実験。",
    categories: ["教育", "ゲーム"],
    status: "archive",
    host: "Web App",
    featured: false,
    visual: "space",
    appUrl: "https://ryotamatsuki.github.io/solar_system/",
    repoUrl: "https://github.com/ryotamatsuki/solar_system"
  }
];
